### PR TITLE
Added package.json for npm support

### PR DESCRIPTION
**Pull request by GrantVisser**

### CODE REVIEW

**Comment by GrantVisser** [comment]
I have also added the package to npm here: https://www.npmjs.com/package/angular-duration-picker

If you would like me to remove this package so that you can upload it yourself, please let me know. All your details and credit goes to you and this repo, just so you know I'm not trying to steal your hard work. :)

**Comment by Yankovsky** [comment]
@GrantVisser Hey! Looks cool. Let me just make some changes.

**Comment by Yankovsky** [comment]
@GrantVisser I don't have permissions to publish the package

**Comment by GrantVisser** [comment]
Give me a second :)

**Comment by GrantVisser** [comment]
@Yankovsky What is your npm username?

Edit: Nevermind, got it on a lucky guess.

**Comment by Yankovsky** [comment]
I'll leave angular dependency as ^1.5.10

**Comment by Yankovsky** [comment]
yankovsky

**Comment by GrantVisser** [comment]
Sounds good!

**Comment by Yankovsky** [comment]
@GrantVisser merged and published again with some changes to package.json, example and bower.json.

**Comment by GrantVisser** [comment]
@Yankovsky Thanks :)

**Pull request merged**
